# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bora

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: bora.azurecr.io
        username: ${{ secrets.acr_bora_username }}
        password: ${{ secrets.acr_bora_password }}
        
    - name: Build and push image to ACR
      id: build-image
      run: |
          docker build . -f  Dockerfile -t bora.azurecr.io/bora:${{ github.sha }} --label dockerfile-path=Dockerfile
          docker push bora.azurecr.io/bora:${{ github.sha }}

  deploy:
    if: true
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bora'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a4b33619bde4b7bba54770d1ed5cc81 }}
        images: 'bora.azurecr.io/bora:${{ github.sha }}'
