name: Docker Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: divagando.azurecr.io
        username: ${{ secrets.acr_divagando_username }}
        password: ${{ secrets.acr_divagando_password }}
        
    - name: Build and push image to ACR
      id: build-image
      run: |
          docker build . -f  Dockerfile -t divagando.azurecr.io/divagando-api:${{ github.sha }} --label dockerfile-path=Dockerfile
          docker push divagando.azurecr.io/divagando-api:${{ github.sha }}
